"use client";
import { useMemo, useState } from "react";

type Application = { postulacion_id:string; oportunidad_id:string; cargo:string; estado:string; nombres:string; apellidos:string; ciudad:string; genero?:string; fecha_nacimiento?:string; puntaje_evaluacion?:number|string; test_risc?:string };
type Job = { oportunidad_id:string; titulo:string; estado:string };
const funnel=["NUEVA","EN REVISION","PRESELECCIONADO","ENTREVISTA","FINALISTA","CONTRATADO"];
// Contorno geográfico de Bolivia, Natural Earth 1:110m (ADM0_A3=BOL).
// Proyección equirectangular local sobre el rectángulo [-69.8,-57.0] × [-23.3,-9.5].
const boliviaOutline = "M37.2 59.4 L56.9 61.7 L70.6 61.2 L76.5 52.9 L99.8 41.9 L113.8 31.7 L148.5 27.1 L145.7 47.5 L148.9 57.9 L146.8 76.1 L175.7 100.5 L205.4 105.0 L215.9 115.1 L233.8 120.5 L244.8 128.4 L261.5 128.1 L276.9 136.2 L278.1 151.9 L283.3 159.8 L283.6 171.6 L275.9 172.0 L286.1 203.6 L337.0 204.8 L333.1 220.5 L336.0 231.2 L350.5 238.8 L356.8 255.7 L352.0 277.1 L344.8 289.0 L347.3 304.5 L339.0 310.1 L338.6 301.7 L313.8 287.9 L289.2 287.5 L242.9 295.4 L230.1 319.3 L229.5 333.9 L219.0 366.4 L214.7 360.6 L184.4 359.5 L174.0 381.4 L158.4 361.7 L123.7 355.1 L101.5 379.7 L82.4 383.4 L72.0 345.9 L57.7 315.5 L66.1 289.2 L52.1 277.7 L48.6 258.0 L35.6 239.6 L52.3 210.2 L40.9 187.4 L47.0 178.3 L42.2 168.2 L52.6 154.6 L53.1 131.5 L54.4 112.4 L60.1 103.2 L37.2 59.4 Z";
const cityCoordinates:Record<string,[number,number]>={"la paz":[-68.1193,-16.4897],"el alto":[-68.165,-16.5],"cochabamba":[-66.1568,-17.3895],"santa cruz":[-63.1806,-17.7833],"sucre":[-65.2592,-19.0333],"potosi":[-65.7531,-19.5723],"oruro":[-67.1149,-17.9833],"tarija":[-64.7296,-21.5355],"trinidad":[-64.9031,-14.8333],"cobija":[-68.7692,-11.0267]};
function project([lon,lat]:[number,number]){return [30+(lon+69.8)/12.8*340,20+(-9.5-lat)/13.8*375];}
function cityKey(s:string){return s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().replace(/,.*$/,"");}
function years(date:string){const d=new Date(date); if(!date||Number.isNaN(d.getTime()))return null;const n=new Date();let y=n.getFullYear()-d.getFullYear();if(n.getMonth()<d.getMonth()||(n.getMonth()===d.getMonth()&&n.getDate()<d.getDate()))y--;return y>=16&&y<=100?y:null;}
function countBy(rows:Application[],key:(a:Application)=>string){const out:Record<string,number>={};rows.forEach(a=>{const k=key(a)||"Sin dato";out[k]=(out[k]||0)+1;});return Object.entries(out).sort((a,b)=>b[1]-a[1]);}
function BarList({items,color="bg-[#477d64]"}:{items:[string,number][];color?:string}){const max=Math.max(1,...items.map(x=>x[1]));return <div className="space-y-3">{items.length===0?<p className="text-sm text-slate-500">Sin datos para este filtro.</p>:items.map(([label,n])=><div key={label}><div className="mb-1 flex justify-between gap-3 text-sm"><span className="truncate">{label}</span><strong>{n}</strong></div><div className="h-2 rounded-full bg-slate-100"><div className={`h-2 rounded-full ${color}`} style={{width:`${n/max*100}%`}}/></div></div>)}</div>}
function MapPanel({rows,title}:{rows:Application[];title:string}){
 const grouped=countBy(rows,a=>cityKey(a.ciudad));
 const missing=grouped.filter(([city])=>!cityCoordinates[city]);
 // La Paz y El Alto comparten área metropolitana: un solo punto impide superponer círculos.
 const metropolitan=grouped.filter(([city])=>city==="la paz"||city==="el alto");
 const plotted=grouped.filter(([city])=>cityCoordinates[city]&&city!=="la paz"&&city!=="el alto");
 if(metropolitan.length)plotted.push([metropolitan.map(([city])=>city).join(" / "),metropolitan.reduce((sum,[,n])=>sum+n,0)]);
 return <section className="rounded-3xl border border-[#d8dfd1] bg-[#fffefa] p-6 shadow-sm"><h3 className="text-lg font-semibold">{title}</h3><p className="mt-1 text-xs text-slate-500">Residencia declarada · tamaño del círculo según el número de personas</p>
 <div className="mt-5 grid items-center gap-5 sm:grid-cols-[1.15fr_.85fr]"><svg viewBox="0 0 390 415" role="img" aria-label={`Mapa geográfico de Bolivia con ${title.toLowerCase()}`} className="w-full rounded-2xl bg-[#e7ece5]"><path d={boliviaOutline} fill="#d3dfd2" stroke="#759b81" strokeWidth="2.2" strokeLinejoin="round"/>
 {plotted.map(([name,n])=>{const coords=name.includes(" / ")?cityCoordinates["la paz"]:cityCoordinates[name];const [x,y]=project(coords);const radius=8+Math.min(13,Math.sqrt(n)*3);return <g key={name}><circle cx={x} cy={y} r={radius+3} fill="white" fillOpacity=".9"/><circle cx={x} cy={y} r={radius} fill="#285c45" fillOpacity=".82"/><text x={x} y={y+4} textAnchor="middle" fill="white" fontSize="12" fontWeight="700">{n}</text><title>{name}: {n}</title></g>})}
 <text x="195" y="407" textAnchor="middle" fill="#466d54" fontSize="11" fontWeight="700" letterSpacing="2">BOLIVIA</text></svg>
 <div className="space-y-2 text-sm">{grouped.length?grouped.map(([city,n])=><div key={city} className="flex justify-between gap-3 border-b border-[#d8dfd1] pb-2"><span className="capitalize">{city}</span><strong>{n}</strong></div>):<p className="text-slate-500">Aún no hay residencias registradas.</p>}{missing.length>0&&<p className="text-xs text-amber-700">{missing.reduce((n,c)=>n+c[1],0)} residencia(s) sin coordenada; aparecen en la lista.</p>}</div></div>
 <p className="mt-4 text-[11px] text-slate-500">Contorno: <a className="underline" href="https://www.naturalearthdata.com/downloads/110m-cultural-vectors/110m-admin-0-countries/" target="_blank" rel="noreferrer">Natural Earth 1:110m</a>. Puntos ubicados por coordenadas de ciudad.</p></section>;
}
export default function Analytics({applications,jobs}:{applications:Application[];jobs:Job[]}){
 const [job,setJob]=useState("TODOS");const [hiredGender,setHiredGender]=useState("TODOS");const [hiredAge,setHiredAge]=useState("TODOS");const rows=useMemo(()=>applications.filter(a=>job==="TODOS"||a.oportunidad_id===job),[applications,job]);
 const hired=rows.filter(a=>a.estado==="CONTRATADO");const assessed=rows.filter(a=>a.puntaje_evaluacion!==""&&a.puntaje_evaluacion!=null&&Number.isFinite(Number(a.puntaje_evaluacion)));
 const hiredMapped=hired.filter(a=>{const y=years(a.fecha_nacimiento||"");const band=y===null?"Sin dato":y<25?"16–24":y<35?"25–34":y<45?"35–44":"45+";return (hiredGender==="TODOS"||(a.genero||"Sin dato")===hiredGender)&&(hiredAge==="TODOS"||band===hiredAge);});
 const alternatives=assessed.filter(a=>!(["CONTRATADO","DESCARTADO"].includes(a.estado))).sort((a,b)=>Number(b.puntaje_evaluacion)-Number(a.puntaje_evaluacion)).slice(0,10);
 const gender=countBy(rows,a=>a.genero||"Sin dato");const city=countBy(rows,a=>cityKey(a.ciudad));const stages=countBy(rows,a=>a.estado);
 const knownAge=hired.map(a=>years(a.fecha_nacimiento||"")).filter((n):n is number=>n!==null);
 const ageGroups=countBy(hired.filter(a=>years(a.fecha_nacimiento||"")!==null),a=>{const y=years(a.fecha_nacimiento||"")!;return y<25?"16–24":y<35?"25–34":y<45?"35–44":"45+";});
 const byGenderJob=countBy(rows,a=>`${a.cargo} · ${a.genero||"Sin dato"}`);
 return <section className="mt-6 space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-[var(--accent-dark)]">Inteligencia de reclutamiento</p><h2 className="mt-1 site-serif text-4xl">Radiografía de postulaciones</h2><p className="text-sm text-slate-500">Los filtros se aplican a todas las visualizaciones.</p></div><select aria-label="Filtrar por cargo" value={job} onChange={e=>setJob(e.target.value)} className="max-w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm"><option value="TODOS">Todos los cargos</option>{jobs.map(j=><option key={j.oportunidad_id} value={j.oportunidad_id}>{j.titulo}</option>)}</select></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Postulaciones",rows.length],["Contratados",hired.length],["En revisión",rows.filter(a=>["NUEVA","EN REVISION"].includes(a.estado)).length],["Con evaluación",assessed.length]].map(([label,value])=><div key={label} className="rounded-2xl border border-[#d8dfd1] bg-[#fffefa] p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-4xl font-bold text-[var(--ink)]">{value}</p></div>)}</div>
 <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-[#d8dfd1] bg-[#fffefa] p-6 shadow-sm"><h3 className="text-lg font-semibold">Género y puesto</h3><p className="mb-5 text-xs text-slate-500">Las respuestas opcionales sin dato se muestran explícitamente.</p><BarList items={byGenderJob}/></section><section className="rounded-3xl border border-[#d8dfd1] bg-[#fffefa] p-6 shadow-sm"><h3 className="text-lg font-semibold">Embudo de selección</h3><p className="mb-5 text-xs text-slate-500">Porcentaje del total en cada estado actual; no representa conversiones históricas.</p><div className="space-y-3">{[...funnel,"DESCARTADO"].map(s=>{const n=rows.filter(a=>a.estado===s).length;return <div key={s} className="flex items-center justify-between gap-3 rounded-xl bg-[#f1f2ea] px-3 py-2"><span className="text-sm">{s}</span><span className="text-sm font-bold">{n} · {rows.length?Math.round(n/rows.length*100):0}%</span></div>})}</div></section></div>
 <div className="grid gap-6 lg:grid-cols-2"><MapPanel rows={rows} title="Postulantes por residencia"/><div><div className="mb-3 flex flex-wrap gap-2"><select aria-label="Género de contratados" value={hiredGender} onChange={e=>setHiredGender(e.target.value)} className="rounded-xl border border-slate-300 bg-white p-2 text-sm"><option value="TODOS">Todos los géneros</option>{[...new Set(hired.map(a=>a.genero||"Sin dato"))].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Edad de contratados" value={hiredAge} onChange={e=>setHiredAge(e.target.value)} className="rounded-xl border border-slate-300 bg-white p-2 text-sm"><option value="TODOS">Todas las edades</option>{["16–24","25–34","35–44","45+","Sin dato"].map(s=><option key={s}>{s}</option>)}</select></div><MapPanel rows={hiredMapped} title="Contratados por residencia"/></div></div>
 <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-[#d8dfd1] bg-[#fffefa] p-6 shadow-sm"><h3 className="text-lg font-semibold">Contrataciones: género y edad</h3><p className="mb-5 text-xs text-slate-500">Edad calculada solo cuando existe fecha de nacimiento.</p><div className="grid gap-6 sm:grid-cols-2"><div><p className="mb-3 text-xs font-bold uppercase text-slate-500">Género</p><BarList items={countBy(hired,a=>a.genero||"Sin dato")}/></div><div><p className="mb-3 text-xs font-bold uppercase text-slate-500">Edad ({knownAge.length} con dato)</p><BarList items={ageGroups} color="bg-[#d49a60]"/></div></div></section><section className="rounded-3xl border border-[#d8dfd1] bg-[#fffefa] p-6 shadow-sm"><h3 className="text-lg font-semibold">Personas contratadas</h3><p className="mb-5 text-xs text-slate-500">Resultado actual del embudo, segmentado por cargo.</p>{hired.length?<div className="space-y-2">{hired.map(a=><div key={a.postulacion_id} className="flex justify-between gap-3 rounded-xl bg-emerald-50 p-3 text-sm"><strong>{a.nombres} {a.apellidos}</strong><span>{a.cargo}</span></div>)}</div>:<p className="text-sm text-slate-500">Aún no hay contratados registrados.</p>}</section></div>
 <section className="rounded-3xl border border-[#d8dfd1] bg-[#fffefa] p-6 shadow-sm"><h3 className="text-lg font-semibold">Candidatos alternativos mejor evaluados</h3><p className="mt-1 text-xs text-slate-500">Ordenados por puntaje; el test RISC se presenta como referencia, sin asignar un peso inventado.</p>{alternatives.length?<div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="py-2">Candidato</th><th>Cargo</th><th>Estado</th><th>Puntaje</th><th>RISC</th></tr></thead><tbody>{alternatives.map(a=><tr key={a.postulacion_id} className="border-b border-slate-100"><td className="py-3 font-semibold">{a.nombres} {a.apellidos}</td><td>{a.cargo}</td><td>{a.estado}</td><td>{a.puntaje_evaluacion}/100</td><td>{a.test_risc||"Pendiente"}</td></tr>)}</tbody></table></div>:<p className="mt-5 text-sm text-slate-500">No hay evaluaciones registradas todavía.</p>}</section>
 <section className="rounded-3xl border border-[#d8dfd1] bg-[#fffefa] p-6 shadow-sm"><h3 className="text-lg font-semibold">Cinco consultas rápidas</h3><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Cargo con más interés",countBy(rows,a=>a.cargo)[0]?.[0]||"Sin datos"],["Ciudad principal",city[0]?.[0]||"Sin datos"],["Género declarado",gender.filter(x=>x[0]!=="Sin dato")[0]?.[0]||"Sin datos"],["Estado más frecuente",stages[0]?.[0]||"Sin datos"],["Tasa de contratación",`${rows.length?Math.round(hired.length/rows.length*100):0}%`]].map(([label,value])=><div key={label} className="rounded-2xl bg-[#f1f2ea] p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 break-words text-base font-semibold capitalize">{value}</p></div>)}</div></section>
 <p className="text-xs text-slate-500">Cobertura: {rows.filter(a=>a.genero).length}/{rows.length} con género, {rows.filter(a=>a.ciudad).length}/{rows.length} con ciudad, {rows.filter(a=>years(a.fecha_nacimiento||"")!==null).length}/{rows.length} con edad. Las coordenadas del mapa son aproximadas.</p>
 </section>;
}
