"use client";
import { useMemo, useState } from "react";

type Application = { postulacion_id:string; oportunidad_id:string; cargo:string; estado:string; nombres:string; apellidos:string; ciudad:string; genero?:string; fecha_nacimiento?:string; puntaje_evaluacion?:number|string; test_risc?:string };
type Job = { oportunidad_id:string; titulo:string; estado:string };
const funnel=["NUEVA","EN REVISION","PRESELECCIONADO","ENTREVISTA","FINALISTA","CONTRATADO"];
const cities:Record<string,[number,number]>={"la paz":[116,137],"el alto":[110,128],"cochabamba":[184,165],"santa cruz":[251,170],"sucre":[200,213],"potosi":[157,233],"oruro":[134,185],"tarija":[189,270],"trinidad":[235,103],"cobija":[175,59]};
function cityKey(s:string){return s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().replace(/,.*$/,"");}
function years(date:string){const d=new Date(date); if(!date||Number.isNaN(d.getTime()))return null;const n=new Date();let y=n.getFullYear()-d.getFullYear();if(n.getMonth()<d.getMonth()||(n.getMonth()===d.getMonth()&&n.getDate()<d.getDate()))y--;return y>=16&&y<=100?y:null;}
function countBy(rows:Application[],key:(a:Application)=>string){const out:Record<string,number>={};rows.forEach(a=>{const k=key(a)||"Sin dato";out[k]=(out[k]||0)+1;});return Object.entries(out).sort((a,b)=>b[1]-a[1]);}
function BarList({items,color="bg-[#477d64]"}:{items:[string,number][];color?:string}){const max=Math.max(1,...items.map(x=>x[1]));return <div className="space-y-3">{items.length===0?<p className="text-sm text-slate-500">Sin datos para este filtro.</p>:items.map(([label,n])=><div key={label}><div className="mb-1 flex justify-between gap-3 text-sm"><span className="truncate">{label}</span><strong>{n}</strong></div><div className="h-2 rounded-full bg-slate-100"><div className={`h-2 rounded-full ${color}`} style={{width:`${n/max*100}%`}}/></div></div>)}</div>}
function MapPanel({rows,title}:{rows:Application[];title:string}){const grouped=countBy(rows,a=>cityKey(a.ciudad));const plotted=grouped.filter(([city])=>cities[city]);const missing=grouped.filter(([city])=>!cities[city]);return <section className="rounded-3xl border border-[#d8dfd1] bg-[#fffefa] p-6 shadow-sm"><h3 className="text-lg font-semibold">{title}</h3><p className="mt-1 text-xs text-slate-500">Mapa esquemático de ciudades de Bolivia · recuento por residencia declarada</p><div className="mt-4 grid items-center gap-4 sm:grid-cols-[1fr_0.8fr]"><svg viewBox="0 0 360 330" role="img" aria-label="Mapa esquemático de Bolivia con postulantes por ciudad" className="w-full rounded-2xl bg-[#e4e9dd]"><path d="M115 25 185 35 220 60 285 71 302 125 319 169 288 215 250 238 223 296 170 304 135 275 112 229 80 211 75 163 48 133 83 90Z" fill="#dce9f7" stroke="#aac4df" strokeWidth="3"/>{plotted.map(([name,n])=>{const [x,y]=cities[name];return <g key={name}><circle cx={x} cy={y} r={9+Math.min(17,n*3)} fill="#477d64" fillOpacity=".76" stroke="white" strokeWidth="3"/><text x={x} y={y-19} textAnchor="middle" fontSize="12" fill="#173c34" fontWeight="700">{name} · {n}</text></g>})}</svg><div className="space-y-2 text-sm">{grouped.length?grouped.map(([city,n])=><div key={city} className="flex justify-between gap-3 border-b border-slate-100 pb-2"><span className="capitalize">{city}</span><strong>{n}</strong></div>):<p className="text-slate-500">Aún no hay residencias registradas.</p>}{missing.length>0&&<p className="text-xs text-amber-700">{missing.reduce((n,c)=>n+c[1],0)} registro(s) sin coordenada en el mapa; aparecen en la lista.</p>}</div></div></section>}
export default function Analytics({applications,jobs}:{applications:Application[];jobs:Job[]}){
 const [job,setJob]=useState("TODOS");const [hiredGender,setHiredGender]=useState("TODOS");const [hiredAge,setHiredAge]=useState("TODOS");const rows=useMemo(()=>applications.filter(a=>job==="TODOS"||a.oportunidad_id===job),[applications,job]);
 const hired=rows.filter(a=>a.estado==="CONTRATADO");const assessed=rows.filter(a=>a.puntaje_evaluacion!==""&&a.puntaje_evaluacion!=null&&Number.isFinite(Number(a.puntaje_evaluacion)));
 const hiredMapped=hired.filter(a=>{const y=years(a.fecha_nacimiento||"");const band=y===null?"Sin dato":y<25?"16–24":y<35?"25–34":y<45?"35–44":"45+";return (hiredGender==="TODOS"||(a.genero||"Sin dato")===hiredGender)&&(hiredAge==="TODOS"||band===hiredAge);});
 const alternatives=assessed.filter(a=>!(["CONTRATADO","DESCARTADO"].includes(a.estado))).sort((a,b)=>Number(b.puntaje_evaluacion)-Number(a.puntaje_evaluacion)).slice(0,10);
 const gender=countBy(rows,a=>a.genero||"Sin dato");const city=countBy(rows,a=>cityKey(a.ciudad));const stages=countBy(rows,a=>a.estado);
 const knownAge=hired.map(a=>years(a.fecha_nacimiento||"")).filter((n):n is number=>n!==null);
 const ageGroups=countBy(hired.filter(a=>years(a.fecha_nacimiento||"")!==null),a=>{const y=years(a.fecha_nacimiento||"")!;return y<25?"16–24":y<35?"25–34":y<45?"35–44":"45+";});
 const byGenderJob=countBy(rows,a=>`${a.cargo} · ${a.genero||"Sin dato"}`);
 return <section className="mt-6 space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-[var(--accent-dark)]">Inteligencia de reclutamiento</p><h2 className="mt-1 site-serif text-4xl">Radiografía de postulaciones</h2><p className="text-sm text-slate-500">Los filtros se aplican a todas las visualizaciones.</p></div><select aria-label="Filtrar por cargo" value={job} onChange={e=>setJob(e.target.value)} className="max-w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm"><option value="TODOS">Todos los cargos</option>{jobs.map(j=><option key={j.oportunidad_id} value={j.oportunidad_id}>{j.titulo}</option>)}</select></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Postulaciones",rows.length],["Contratados",hired.length],["En revisión",rows.filter(a=>["NUEVA","EN REVISION"].includes(a.estado)).length],["Con evaluación",assessed.length]].map(([label,value])=><div key={label} className="rounded-2xl border border-[#d8dfd1] bg-[#fffefa] p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-4xl font-bold text-[var(--ink)]">{value}</p></div>)}</div>
 <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-[#d8dfd1] bg-[#fffefa] p-6 shadow-sm"><h3 className="text-lg font-semibold">Género y puesto</h3><p className="mb-5 text-xs text-slate-500">Las respuestas opcionales sin dato se muestran explícitamente.</p><BarList items={byGenderJob}/></section><section className="rounded-3xl border border-[#d8dfd1] bg-[#fffefa] p-6 shadow-sm"><h3 className="text-lg font-semibold">Embudo de selección</h3><p className="mb-5 text-xs text-slate-500">Porcentaje del total en cada estado actual; no representa conversiones históricas.</p><div className="space-y-3">{[...funnel,"DESCARTADO"].map(s=>{const n=rows.filter(a=>a.estado===s).length;return <div key={s} className="flex items-center justify-between gap-3 rounded-xl bg-[#f1f2ea] px-3 py-2"><span className="text-sm">{s}</span><span className="text-sm font-bold">{n} · {rows.length?Math.round(n/rows.length*100):0}%</span></div>})}</div></section></div>
 <div className="grid gap-6 lg:grid-cols-2"><MapPanel rows={rows} title="Postulantes por residencia"/><div><div className="mb-3 flex flex-wrap gap-2"><select aria-label="Género de contratados" value={hiredGender} onChange={e=>setHiredGender(e.target.value)} className="rounded-xl border border-slate-300 bg-white p-2 text-sm"><option value="TODOS">Todos los géneros</option>{[...new Set(hired.map(a=>a.genero||"Sin dato"))].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Edad de contratados" value={hiredAge} onChange={e=>setHiredAge(e.target.value)} className="rounded-xl border border-slate-300 bg-white p-2 text-sm"><option value="TODOS">Todas las edades</option>{["16–24","25–34","35–44","45+","Sin dato"].map(s=><option key={s}>{s}</option>)}</select></div><MapPanel rows={hiredMapped} title="Contratados por residencia"/></div></div>
 <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-[#d8dfd1] bg-[#fffefa] p-6 shadow-sm"><h3 className="text-lg font-semibold">Contrataciones: género y edad</h3><p className="mb-5 text-xs text-slate-500">Edad calculada solo cuando existe fecha de nacimiento.</p><div className="grid gap-6 sm:grid-cols-2"><div><p className="mb-3 text-xs font-bold uppercase text-slate-500">Género</p><BarList items={countBy(hired,a=>a.genero||"Sin dato")}/></div><div><p className="mb-3 text-xs font-bold uppercase text-slate-500">Edad ({knownAge.length} con dato)</p><BarList items={ageGroups} color="bg-[#d49a60]"/></div></div></section><section className="rounded-3xl border border-[#d8dfd1] bg-[#fffefa] p-6 shadow-sm"><h3 className="text-lg font-semibold">Personas contratadas</h3><p className="mb-5 text-xs text-slate-500">Resultado actual del embudo, segmentado por cargo.</p>{hired.length?<div className="space-y-2">{hired.map(a=><div key={a.postulacion_id} className="flex justify-between gap-3 rounded-xl bg-emerald-50 p-3 text-sm"><strong>{a.nombres} {a.apellidos}</strong><span>{a.cargo}</span></div>)}</div>:<p className="text-sm text-slate-500">Aún no hay contratados registrados.</p>}</section></div>
 <section className="rounded-3xl border border-[#d8dfd1] bg-[#fffefa] p-6 shadow-sm"><h3 className="text-lg font-semibold">Candidatos alternativos mejor evaluados</h3><p className="mt-1 text-xs text-slate-500">Ordenados por puntaje; el test RISC se presenta como referencia, sin asignar un peso inventado.</p>{alternatives.length?<div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="py-2">Candidato</th><th>Cargo</th><th>Estado</th><th>Puntaje</th><th>RISC</th></tr></thead><tbody>{alternatives.map(a=><tr key={a.postulacion_id} className="border-b border-slate-100"><td className="py-3 font-semibold">{a.nombres} {a.apellidos}</td><td>{a.cargo}</td><td>{a.estado}</td><td>{a.puntaje_evaluacion}/100</td><td>{a.test_risc||"Pendiente"}</td></tr>)}</tbody></table></div>:<p className="mt-5 text-sm text-slate-500">No hay evaluaciones registradas todavía.</p>}</section>
 <section className="rounded-3xl border border-[#d8dfd1] bg-[#fffefa] p-6 shadow-sm"><h3 className="text-lg font-semibold">Cinco consultas rápidas</h3><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Cargo con más interés",countBy(rows,a=>a.cargo)[0]?.[0]||"Sin datos"],["Ciudad principal",city[0]?.[0]||"Sin datos"],["Género declarado",gender.filter(x=>x[0]!=="Sin dato")[0]?.[0]||"Sin datos"],["Estado más frecuente",stages[0]?.[0]||"Sin datos"],["Tasa de contratación",`${rows.length?Math.round(hired.length/rows.length*100):0}%`]].map(([label,value])=><div key={label} className="rounded-2xl bg-[#f1f2ea] p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 break-words text-base font-semibold capitalize">{value}</p></div>)}</div></section>
 <p className="text-xs text-slate-500">Cobertura: {rows.filter(a=>a.genero).length}/{rows.length} con género, {rows.filter(a=>a.ciudad).length}/{rows.length} con ciudad, {rows.filter(a=>years(a.fecha_nacimiento||"")!==null).length}/{rows.length} con edad. Las coordenadas del mapa son aproximadas.</p>
 </section>;
}
