import Link from "next/link";
import { ArrowRight, ArrowUpRight, Compass, GlobeHemisphereWest, Sparkle, UsersThree } from "@phosphor-icons/react/dist/ssr";

const steps = [
  { no: "01", title: "Descubre", text: "Explora las oportunidades abiertas y encuentra el equipo donde puedes crecer.", icon: Compass },
  { no: "02", title: "Preséntate", text: "Comparte tu experiencia, formación y la historia detrás de tu perfil.", icon: UsersThree },
  { no: "03", title: "Conectemos", text: "Nuestro equipo revisará tu postulación y continuará el proceso contigo.", icon: Sparkle },
];

export default function HomePage() {
  return <main className="site-shell min-h-screen overflow-hidden">
    <div className="site-noise" aria-hidden="true" />
    <header className="site-header relative z-10 mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10">
      <Link href="/home" className="site-brand"><span className="site-brand-mark">LA<span>.</span></span><span className="hidden text-[11px] font-bold uppercase leading-tight tracking-[.18em] sm:block">Los Andes<br/>Talento</span></Link>
      <nav className="flex items-center gap-2 text-sm font-semibold sm:gap-6"><Link className="hidden transition hover:text-[var(--accent)] sm:block" href="/home">Inicio</Link><Link className="hidden transition hover:text-[var(--accent)] sm:block" href="/postulate">Oportunidades</Link><Link className="site-nav-cta" href="/admin">Acceso RR. HH. <ArrowUpRight size={16}/></Link></nav>
    </header>
    <section className="relative mx-auto grid max-w-7xl items-center gap-12 px-6 pb-20 pt-16 lg:grid-cols-[1.12fr_.88fr] lg:px-10 lg:pb-28 lg:pt-24">
      <div className="relative z-10"><div className="site-eyebrow"><span className="site-dot"/> Personas que hacen posible lo que viene</div><h1 className="site-display mt-7 max-w-[800px] text-[clamp(4.4rem,9vw,8.8rem)] leading-[.88]">Hay un lugar<br/>para <em>tu</em><br/>talento<span className="text-[var(--accent)]">.</span></h1><p className="mt-9 max-w-lg text-lg leading-8 text-[var(--ink-soft)]">En Los Andes creemos en las personas que se animan a dar el siguiente paso. Descubre dónde puede comenzar tu próxima historia.</p><div className="mt-10 flex flex-wrap items-center gap-5"><Link href="/postulate" className="site-button">Explorar vacantes <ArrowUpRight size={20}/></Link><span className="text-sm font-medium text-[var(--ink-soft)]">Tu siguiente oportunidad te espera</span></div></div>
      <div className="relative hidden min-h-[580px] lg:block"><div className="absolute inset-6 rotate-[-7deg] rounded-[200px_200px_24px_24px] border border-[var(--ink)]/15"/><div className="site-portrait absolute inset-0 overflow-hidden rounded-[200px_200px_24px_24px]"><div className="absolute inset-x-0 bottom-0 h-1/2 bg-gradient-to-t from-[#173c34]/60 to-transparent"/><div className="absolute bottom-10 left-9 right-9 text-white"><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em]"><span className="h-2 w-2 rounded-full bg-[var(--accent)]"/> El futuro se construye juntos</div><p className="site-serif text-4xl leading-tight">Personas primero.<br/>Siempre.</p></div></div><div className="absolute -bottom-5 -left-12 flex h-36 w-36 rotate-[-13deg] flex-col justify-center rounded-full bg-[var(--accent)] px-7 text-[var(--ink)] shadow-2xl"><Sparkle size={24} weight="fill"/><span className="mt-1 text-sm font-bold leading-4">Nuevas<br/>oportunidades</span></div></div>
    </section>
    <div className="site-marquee border-y border-[var(--ink)]/15 bg-[#e4e9dd] py-4"><div className="mx-auto flex max-w-7xl items-center justify-between gap-5 overflow-hidden px-6 text-xs font-bold uppercase tracking-[.22em] text-[#285447] lg:px-10"><span>Impulsa tu carrera</span><span className="hidden sm:inline">·</span><span>Crece con nosotros</span><span className="hidden sm:inline">·</span><span>Construyamos futuro</span><span className="hidden md:inline">·</span><span className="hidden md:inline">Los Andes · Bolivia</span></div></div>
    <section className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr] lg:gap-16"><div><div className="site-eyebrow">Una forma sencilla de comenzar</div><h2 className="site-serif mt-5 text-5xl leading-[1.04] sm:text-6xl">Tu camino<br/>empieza <em>hoy.</em></h2><p className="mt-6 max-w-sm leading-7 text-[var(--ink-soft)]">Un proceso pensado para conocer lo que sabes hacer y lo que quieres lograr.</p></div><div className="divide-y divide-[var(--ink)]/15 border-t border-[var(--ink)]/15">{steps.map(({no,title,text,icon:Icon})=><div key={no} className="group grid grid-cols-[50px_1fr_42px] items-start gap-4 py-7 sm:grid-cols-[70px_1fr_42px]"><span className="site-serif text-2xl text-[var(--accent-dark)]">{no}</span><div><h3 className="site-serif text-3xl">{title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-[var(--ink-soft)]">{text}</p></div><Icon className="mt-1 text-[var(--accent-dark)] transition group-hover:rotate-12" size={26} weight="duotone"/></div>)}</div></div></section>
    <section className="bg-[var(--ink)] px-6 py-20 text-[#f6f2e9] lg:px-10"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-10 lg:flex-row lg:items-end"><div><div className="site-eyebrow !text-[#b9d2b9]"><GlobeHemisphereWest size={17}/> Talento en movimiento</div><h2 className="site-serif mt-5 max-w-3xl text-5xl leading-[1.05] sm:text-7xl">Lo que sigue puede<br/>empezar <em>contigo.</em></h2></div><Link href="/postulate" className="site-button !bg-[var(--accent)] !text-[var(--ink)]">Ver oportunidades <ArrowRight size={21}/></Link></div></section>
    <footer className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-6 py-8 text-sm text-[var(--ink-soft)] lg:px-10"><span className="font-bold text-[var(--ink)]">LOS ANDES / TALENTO</span><span>Personas. Potencial. Futuro.</span><span>Bolivia · 2026</span></footer>
  </main>;
}
